# Generated by Django 5.0.2 on 2024-11-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
